---
title: "formula1_allyears"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("hyper2")
```

## Introduction

*Takes about 20 minutes to run with no cache*

Here I analyse Formula 1 results 2010-2019 using Plackett-Luce
likelihoods as implemented in the `hyper2` package.  Files like
`formula1_2017.txt` are directly copied from Wikipedia (with slight
whitespace changes).


```{r,label=f1yearsseparate,cache=TRUE}
f <- function(M){M[,-ncol(M)]} # removes 'points' column
o <- function(k){ordertable2supp(f(read.table(k)))}
F1_2010 <- o("formula1_2010.txt")
F1_2011 <- o("formula1_2011.txt")
F1_2012 <- o("formula1_2012.txt")
F1_2013 <- o("formula1_2013.txt")
F1_2014 <- o("formula1_2014.txt")
F1_2015 <- o("formula1_2015.txt")
F1_2016 <- o("formula1_2016.txt")
F1_2017 <- o("formula1_2017.txt")
F1_2018 <- o("formula1_2018.txt")
F1_2019 <- o("formula1_2019.txt")
```

```{r,label=combineallyears,cache=TRUE}
F1_list<- list(F1_2010, F1_2011, F1_2012, F1_2013, F1_2014, F1_2015, F1_2016, F1_2017, F1_2018, F1_2019)
F1_total <- F1_2010 + F1_2011 + F1_2012 + F1_2013 + F1_2014 + F1_2015 + F1_2016 + F1_2017 + F1_2018 + F1_2019
```

```{r,calculatemaxlikelhood,cache=TRUE}
m <- maxp(F1_total)
pie(m)
dotchart(m,pch=16,main='Formula 1, 2012-9')
```

```{r,workwithM}
M <- matrix(NA,length(pnames(F1_total)),2019-2010+1)
rownames(M) <- pnames(F1_total)
colnames(M) <- paste("y",10:19,sep="")

for(i in seq_len(nrow(M))){
    for(j in seq_len(ncol(M))){
        if(rownames(M)[i] %in% pnames(F1_list[[j]])){M[i,j] <- 1}
    }
}
jj <- order(rowSums(M,na.rm=T),decreasing=T)
M <- M[jj,]

image(x=2010:2019,y=seq_along(pnames(F1_total)),t(M))
```


```{r}
howmanyraces <- sort(rowSums(M,na.rm=TRUE),decreasing=TRUE)
plot(howmanyraces)
```

```{r}
select <- function(F1tab,minraces=5){
	wanted <- rownames(M)[howmanyraces >= minraces]
	ordertable2supp(F1tab[rownames(F1tab) %in% wanted,])
}
```


```{r,definefreqrace}
freqracers <- function(minraces){
(
	select(f(read.table("formula1_2010.txt")),minraces) + 
	select(f(read.table("formula1_2011.txt")),minraces) + 
	select(f(read.table("formula1_2012.txt")),minraces) + 
	select(f(read.table("formula1_2013.txt")),minraces) + 
	select(f(read.table("formula1_2014.txt")),minraces) + 
	select(f(read.table("formula1_2015.txt")),minraces) + 
	select(f(read.table("formula1_2016.txt")),minraces) + 
	select(f(read.table("formula1_2017.txt")),minraces) + 
	select(f(read.table("formula1_2018.txt")),minraces) 
	)
}

comp <- function(m,mr){
	par(pty="s")
#	plot(m,mr,asp=1,xlim=c(0,0.2),ylim=c(0,0.2))
	plot(m,mr,asp=1)
	abline(0,1)
}
```


# All drivers

```{r,freqtop1,cache=TRUE}
F1_top1 <- freqracers(1)
m1 <- maxp(F1_top1)
pnames(F1_top1) <- rev(pnames(F1_top1))
m1r <- rev(maxp(F1_top1)) # reverse of MLE with names reversed
```


```{r}
pie(m1)
comp(m1,m1r)
```

# Drivers with >= 2 races

```{r,freqtop2,cache=TRUE}
F1_top2 <- freqracers(2)
m2 <- maxp(F1_top2)
pnames(F1_top2) <- rev(pnames(F1_top2))
m2r <- rev(maxp(F1_top2)) # reverse of MLE with names reversed
```


```{r}
pie(m2)
comp(m2,m2r)
```

# Drivers with >= 3 races

```{r,freqtop3,cache=TRUE}
F1_top3 <- freqracers(3)
m3 <- maxp(F1_top3)
pnames(F1_top3) <- rev(pnames(F1_top3))
m3r <- rev(maxp(F1_top3)) # reverse of MLE with names reversed
```


```{r}
pie(m3)
comp(m3,m3r)
```

# Drivers with >= 4 races

```{r,freqtop4,cache=TRUE}
F1_top4 <- freqracers(4)
m4 <- maxp(F1_top4)
pnames(F1_top4) <- rev(pnames(F1_top4))
m4r <- rev(maxp(F1_top4)) # reverse of MLE with names reversed
```


```{r}
pie(m4)
comp(m4,m4r)
```


# Drivers with >= 5 races

```{r,freqtop5,cache=TRUE}
F1_top5 <- freqracers(5)
m5 <- maxp(F1_top5)
pnames(F1_top5) <- rev(pnames(F1_top5))
m5r <- rev(maxp(F1_top5)) # reverse of MLE with names reversed
```


```{r}
pie(m5)
comp(m5,m5r)
```


# Drivers with >= 6 races

```{r,freqtop6,cache=TRUE}
F1_top6 <- freqracers(6)
m6 <- maxp(F1_top6)
pnames(F1_top6) <- rev(pnames(F1_top6))
m6r <- rev(maxp(F1_top6)) # reverse of MLE with names reversed
```


```{r}
pie(m6)
comp(m6,m6r)
```


