---
title: "Javelins with hyper3 objects"
author: "Robin KS Hankin"
date: "10/04/2022"
output: html_document
---

```{r setup, include=FALSE}
set.seed(1)
knitr::opts_chunk$set(echo = TRUE)
library("hyper2")
library("disordR")
```


`https://en.wikipedia.org/w/index.php?title=Athletics_at_the_2020_Summer_Olympics_%E2%80%93_Men%27s_javelin_throw&oldid=1051014985`


```{r,label=loadjavelinandconvert}
javelin_table <- read.table("javelin.txt",header=TRUE)
a <- javelin_table # saves typing

o <- attemptstable2supp3(a,decreasing=TRUE,give.supp=FALSE)
```

Plot the data in visual form:

```{r, label=plotjav}
n <- length(levels(as.factor(names(o))))
plot(o,pch=16,col=rainbow(n)[as.factor(names(o))])
legend("topright",pch=16,col=rainbow(n),legend=levels(as.factor(names(o))))
```

Now process it:

```{r,label=dothething1,cache=TRUE}    	   
javelin <- attemptstable2supp3(a,decreasing=TRUE,give.supp=TRUE)
H1 <- javelin # saves typing
javelin1_maxp <- maxp(H1)
m1 <- javelin1_maxp
```


```{r,label=dothething2,cache=TRUE}    	   
H2 <- ordervec2supp3(v=names(o)[!is.na(o)])
javelin2_maxp  <- maxp(H2)
m2 <- javelin2_maxp
```

```{r,plotm}
pie(m1)
pie(m2)
dotchart(m1,pch=16)
dotchart(m2,pch=16)
par(pty="s")
plot(m1,m2,pch=16,type="p",asp=1)
abline(0,1)
```



### Package dataset {-}

Following lines create `javelin.rda`, residing in the `data/`
directory of the package.

```{r,label=savejavelindataset}
save(javelin,javelin_table,javelin1_maxp,javelin2_maxp,  file="javelin.rda")
```

