---
title: "Red bus, blue bus"
output: pdf_document
bibliography: chess.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The red bus-blue bus problem was originally stated by @chipman1960 and
discussed by @davidson1970 and @alvo2010 (page 153).


The other one was the holiday problem.

A traveller has a choice of going to work by car or taking a bus.  The
bus may be red or blue.  Here, we assume that the traveller has strong
(but unknown) views on cars vs buses.  If considering a car or bus,
the colour of the bus is of no importance to him.  
However, when offered the choice between a red bus or a blue bus, the
colour becomes important (having nothing else to guide his decision).

A sensible likelihood function is shown in figure \ref{likefuncred}.

\begin{table}[h]
\centering
\caption{Likelihoods\label{likefuncred} for red bus, blue bus problem}
\begin{tabular}{|l|l|}
\hline
Choice set & likelihood  \\ \hline
$\left\lbrace C,RB  \right\rbrace$ & $\left(\frac{p_C   }{p_C+p_{B}   }\right)^a \left(\frac{p_{B}}{p_C+p_{B}}\right)^b $ \\ \hline
$\left\lbrace C,BB  \right\rbrace$ & $\left(\frac{p_C   }{p_C+p_{B}   }\right)^c \left(\frac{p_{B}}{p_C+p_{B}}\right)^d $ \\ \hline
$\left\lbrace RB,BB \right\rbrace$ & $\left(\frac{1}{2}\right)^e 
                                      \left(\frac{1}{2}\right)^f
$ \\ \hline
$\left\lbrace C,RB,BB\right\rbrace$ & $
\left(\frac{p_C}{p_C + 2p_{B}}\right)^g
\left(\frac{p_B}{p_C + 2p_{B}}\right)^h
\left(\frac{p_B}{p_C + 2p_{B}}\right)^i
$\\ \hline
\end{tabular}
\end{table}

\begin{table}[h]
\centering
\caption{Likelihoods\label{likefuncredghost} for red bus, blue bus problem}
\begin{tabular}{|l|l|}
\hline
Choice set & likelihood  \\ \hline
$\left\lbrace C,RB  \right\rbrace$ & $\left(\frac{p_C   }{p_C+p_{B}   }\right)^a \left(\frac{p_{B}}{p_C+p_{B}}\right)^b $ \\ \hline
$\left\lbrace C,BB  \right\rbrace$ & $\left(\frac{p_C   }{p_C+p_{B}   }\right)^c \left(\frac{p_{B}}{p_C+p_{B}}\right)^d $ \\ \hline
$\left\lbrace RB,BB \right\rbrace$ & $\left(\frac{p_{B}+p_{RG}}{2p_{B}+p_{RG}}\right)^e 
                                      \left(\frac{p_{B}       }{2p_{B}+p_{RG}}\right)^f
$ \\ \hline
$\left\lbrace C,RB,BB\right\rbrace$ & $
\left(\frac{p_C       }{p_C + 2p_{B}+p_{RG}}\right)^g
\left(\frac{p_B+p_{RG}}{p_C + 2p_{B}+p_{RG}}\right)^h
\left(\frac{p_B       }{p_C + 2p_{B}+p_{RG}}\right)^i
$\\ \hline
\end{tabular}
\end{table}



 @debreu1960 offers:
 
Let the set U have the following three elements: $D_c$, a recording of
the Debussy quartet by the $C$ quartet, $B_F$, a recording of the
eighth symphony of Beethoven by the $B$ orchestra conducted by $F$,
$B_K$, a recording of the eighth symphony of Beethoven by the $B$
orchestra conducted by $K$.  The subject will be presented with a
subset of $U$, will be asked to choose an element in that subset, and
will listen to the recording he has chosen.  When presented with
$\left\lbrace D_c, B_F\right\rbrace$, he chooses $D_c$ with
probability $\frac{3}{5}$.  When presented with $\lbrace BF,
BK\rbrace$ he chooses $B_F$ with probability 1/2. When presented with
$\left\lbrace DC, BK\right\rbrace$ he chooses $D_c$ with probability
$\frac{3}{5}$.  What happens if he is presented with $\lbrace D_c,
B_F, B_K\rbrace$?  According to the axiom, he must choose $D_c$ with
probability 3/7.  Thus if he can choose between $D_c$ and $B_F$, he
would rather have Debussy.  However if he can choose between $D_c$,
$B_F$, and $B_K$, while being indifferent between $B_F$ and $B_K$, he
would rather have Beethoven.



THERE IS ALSO THE THING WITH THE HOLIDAY IN CALIFORNIA AND THE HOLIDAY
IN FLORIDA AND THE HOLIDAY IN FLORIDA PLUS TEN BUCKS

```
a,b,c in a race; a and b have an advantage S

finishing order a>b>c:   L = (a+S)/(a+b+c+2S) * (b+S)/(b+c+ S)
finishing order a>c>b:   L = (a+S)/(a+b+c+2S) * (c  )/(a+b+2S)
finishing order c>a>b:   L = (c  )/(a+b+c+2S) * (a+S)/(a+b+2S)


a,b,c,d in teams {a,b} and {c,d}


{a+b} wins, a and c have S:       (a+b+S)/(a+b+c+d+2S)
{a+b} wins, c and d have S:       (a+b)/(a+b+c+d+2S)
{a+b} wins, a and b have S:       (a+b+2S)/(a+b+c+d+2S)
{a+b} wins, a and b and c have S:  (a+b+2S)/(a+b+c+d+3S)



Car, red bus blue bus:

C  wins:  2C/(2C+RB+BB)
RB wins:  RB/(2C+RB+BB)
BB wins:  BB/(2C+RB+BB)

[NB if red and blue are really equivalent, then RB=BB=B, say and we have

C wins:  C/(C+B)
RB wins: B/(2C+2B) = 0.5*B/(C+B)
BB wins: B/(2C+2B) = 0.5*B/(C+B)


holidays:  Florida, California, California plus a nickel:



{F,C}       :  (F,C)/(F+C)  # nickel ignored in likelihood function
{F,CN}      :  (F,C)/(F+C)  # nickel ignored in likelihood function
{FN,C}      :  (F,C)/(F+C)  # nickel ignored in likelihood function
{FN,CN}     :  (F,C)/(F+C)  # nickel ignored in likelihood function

{F,FN}      :  (F,F+N)/(2F+N)
{C,CN}      :  (C,C+N)/(2C+N)

{F,C,CN}    :  (F,C,C+N)/(F+2C+N)   # FN missing
{F,FN,C}    :  (F,F+N,C)/(2F+C+N)   # CN missing

{FN,C,CN}   :  (F,C,C+N)/(F+2C+N)   # F missing
{F,FN,CN}   :  (F,F+N,C)/(2F+C+N)   # C missing

{F,FN,C,CN} :  (F,F+N,C,C+N)/(2F+2C+2N)  ??????????????

Last line (viz {F,FN,C,CN} is problematic.  Suppose that N is actually
important [as in, eg {F,FN} and N=0.999] but also N is immaterial when
comparing Florida with California.  This is a perfectly reasonable
scenario.  Then in the last line we have pretty much 50-50 probability
between {F+N,C+N}.  But this is not consistent with {F,C} which shows
that the chooser is not indifferent between Florida and California.
He might be 75% Florida and 25% California; and if this is the case we
should have {F,C} = (0.75,0.25) and {FN,CN}= (0.75,0.25) [because the
Nickel is immaterial when comparing F and C].  So what we need is for
{F,F+N,C,C+N} and N=0.999 to reduce to {F+N,C+N} which itself should
reduce to {F,C}.  And the last line above has {F,FN,C,CN} =
(0,0.5,0,0.5) which is effectively stating that he is indifferent
between Florida and California, or at least they have equal BT
strength.  This probability model is flawed because the only effect of
the nickel in {F,FN,C,CN} should be to reduce the probability of F and
C and {FN,CN} should be (F,C).


The correct probability model is to use a two-stage process as
follows:

{F,FN,FC,CN}  :  p(F)  = F/(F+C) * F/(F+N)
              :  p(FN) = F/(F+C) * N/(F+N) 
              :  p(C)  = C/(F+C) * C/(C+N) 
              :  p(CN) = C/(F+C) * N/(C+N)


Then

{F,C,CN}    :  p(F)  = F/(F+C)
            :  p(C)  = C/(F+C) * C/(C+N)
            :  p(CN) = C/(F+C) * N/(C+N)

etc.


Try this approach with red bus blue bus:


L = L(C,B,red,blue)

{C,RB}    : p(C)  = C/(C+B)
{C,RB}    : p(RB) = B/(C+B)

{C,BB}    : p(C)  = C/(C+B)
{C,BB}    : p(BB) = B/(C+B)  # (same as above)

{RB,BB}   : p(RB) =  red/(red+blue)
          : p(BB) = blue/(red+blue)

{C,RB,BB} :  p(C)  = C/(C+B) 
{C,RB,BB} :  p(RB) = B/(C+B) * red/(red+blue)
{C,RB,BB} :  p(BB) = B/(C+B) * blue/(red+blue)
```



# References

