---
title: "simplified_likelihood"
author: "Robin Hankin"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Consider a race between $n+2$ competitors of strength $p_1$, $p_2$, and $n$ clones, all of strength $p=1-p_1-p_2$.  Our observation is that $p_1$ places $n_1$, and $p_2$ places $n_2>n_1$.  The order statistic is thus

$$
\underbrace{p\succ\cdots\succ p}_{\mbox{$n_1-1$ terms}}\succ p_1\succ\underbrace{p\succ\cdots\succ p}_{n_2-n_1-1}\succ p_2\succ\underbrace{p\succ\cdots\succ p}_{n-n_2+2}
$$

The Plackett-Luce likelihood function would be as follows

$$
\begin{eqnarray}
&{}&
\underbrace{
\frac{p}{p_1+p_2+np}\cdot
\frac{p}{p_1+p_2+(n-1)p}
\cdots
\frac{p}{p_1+p_2+(n-n_1+2)p}
}_{n_1-1}\cdot\\&{}&
\frac{p_1}{p_1+p_2+(n-n_1+1)p}\cdot\\&{}&
\underbrace{
\frac{p}{p_2+(n-n_1+1)p}\cdot
\frac{p}{p_2+(n-n_1)p}\cdots
\frac{p}{p_2+(n-n_2+3)p}
}_{n_2-n_1-1}\cdot\\&{}&
\frac{p_2}{p_2+(n-n_2+2)p}\cdot\\&{}&
\underbrace{
\frac{p}{(n-n_2+2)p}\cdot\frac{p}{(n-n_2)p}
\cdots\frac{p}{2p}\cdot\frac{p}{p}
}_{n-n_2+2}
\end{eqnarray}
$$

Observing that the fifth line may be neglected, R idiom for this would be as follows

```{r}
library("hyper2")
simplike_lowlevel <- function(n1,n2,n,p1="p1",p2="p2",other="other"){
  stopifnot(n1<n2)
  H <- hyper3()
  H[setNames(1,other)] <- n2-2
  H[setNames(1,p1)] <- 1
  H[setNames(1,p2)] <- 1
  for(i in (n-n1+1):n){H[setNames(c(1,1,i),c(p1,p2,other))]  %<>% dec }
  for(i in (n-n2+2):(n-n1+1)){H[setNames(c(1,i),c(p2,other))] %<>% dec }
  return(H)
}

twodrivers <- function(...,n){ # twodrivers(ham=3, bottas=5,n=20)
  L <- list(...)
  stopifnot(length(L)==2)
  if(L[[1]] > L[[2]]){ # wrong way round
    tmp <- L[[2]]
    L[[2]] <- L[[1]]
    L[[1]] <- tmp
    names(L) <- rev(names(L))
  }
  simplike_lowlevel(as.numeric(L[[1]]),as.numeric(L[[2]]),n,names(L)[1],names(L)[2])
}

twodrivers(o=2,XX=6,n=11)
```

Now 

```{r readtable}
a <- read.table("formula1_2019.txt")[1:2,1:21]
a
f <- function(i){
  jj <- as.list(a[,i])
  names(jj) <- rownames(a)
  return(jj)
}

H <- hyper3()
for(i in seq_len(ncol(a))){
  jj <- f(i)
  if(all(!is.na(as.numeric(unlist(jj))))){
    H <- H + do.call(twodrivers,c(jj,n=20))
  }
}
H
```

```{r maxh,cache=TRUE}
maxp(H)
```

```{r equaltest,cache=TRUE}
samep.test(H,c("Hamilton","Bottas"))
```

