# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

identityL <- function(L, p) {
    .Call('hyper2_identityL', PACKAGE = 'hyper2', L, p)
}

addL <- function(L1, p1, L2, p2) {
    .Call('hyper2_addL', PACKAGE = 'hyper2', L1, p1, L2, p2)
}

equality <- function(L1, p1, L2, p2) {
    .Call('hyper2_equality', PACKAGE = 'hyper2', L1, p1, L2, p2)
}

accessor <- function(L, powers, Lwanted) {
    .Call('hyper2_accessor', PACKAGE = 'hyper2', L, powers, Lwanted)
}

overwrite <- function(L1, powers1, L2, powers2) {
    .Call('hyper2_overwrite', PACKAGE = 'hyper2', L1, powers1, L2, powers2)
}

assigner <- function(L, p, L2, value) {
    .Call('hyper2_assigner', PACKAGE = 'hyper2', L, p, L2, value)
}

evaluate <- function(L, powers, probs) {
    .Call('hyper2_evaluate', PACKAGE = 'hyper2', L, powers, probs)
}

differentiate <- function(L, powers, probs, n) {
    .Call('hyper2_differentiate', PACKAGE = 'hyper2', L, powers, probs, n)
}

