name: Build and deploy hyper2 site

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RSTUDIO_PANDOC: /opt/hostedtoolcache/pandoc

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: setup tinyTex
        uses: r-lib/actions/setup-tinytex@v2
      
      - name: Tell R where pandoc is 
        run: |
          echo "RSTUDIO_PANDOC=$(dirname $(which pandoc))" >> $GITHUB_ENV
      
      - name: Install system deps (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagick++-dev

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            rmarkdown
            digest
            tikzDevice
            magick
          needs: none

      - name: copy txt files to root directory
        run: |
          find inst/ -type f -name "*.txt" -exec cp {} . \;

      - name: Build site
        run: |
          R -q -e "Sys.setenv(RSTUDIO_PANDOC = dirname(Sys.which('pandoc'))); source('inst/build_site.R')"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: inst/site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
